executionOrder:
  continueOnFailure: false # default is true
  flowsOrder:
    - 0001-Activation.yaml
    - 0002-Login_failed.yaml
    - 0003-Clock_in_out.yaml
    - 0004-Basic_Transaction_Processing.yaml
    - 0005-Enable_Table_layout.yaml
    - 0006-Login_success.yaml
    - 0010-Make_transaction.yaml
    - 0020-Search_product.yaml
    - 0999-Deactivate.yaml
